GP-28
AHU-Graduation-Project/Graduation-Project pull request #30
Opened 2024-12-10 22:13 UTC by kafkacs

new login and sign up page fully functional with a separated background (particles animated) 
tell me if there are any needed changes.
thank you.

<img width="1429" alt="Screen Shot 2024-12-11 at 1 02 21 AM" src="https://github.com/user-attachments/assets/f92fbc6d-0c80-40ca-9939-d7c46e2f352d">

<img width="1440" alt="Screen Shot 2024-12-03 at 9 49 14 PM" src="https://github.com/user-attachments/assets/48dc8b3c-1521-47fe-a3eb-82e3ca89c545">

2024-12-19 23:59 UTC, ahmad-abdelraheem requested changes
Thanks for the great effort, @kafkacs! Please update this PR to align with the design provided by Tuqa, as the form block and transitions are significantly different. Additionally, kindly take a look at my comments and let me know once you’ve addressed them so I can re-review.

Also, please ensure unit tests maintain at least **80%** coverage, as this is very important for our project and will enhance your knowledge as well for your career.

2024-12-19 23:59 UTC, ahmad-abdelraheem commented on FrontEnd/src/pages/Login.tsx
1. Move the forms into separated components (` LoginForm `, ` SignupForm ` ...etc.).
2. I believe that tailwind can be used in more clear way. Try to group the most used classes in a string variable instead of duplicate the same code on each input.
3. ` input ` is used 5 times in this file only, so let's build an Input component. Make sure that the component can be used in all cases using different props.
4. While we have 8 components on this file, and it's a widely used component. Can we build a ` Button ` component or at least direct global classes such as `btn`, `btn-primary` and so on ?
5. Lets create an ` auth ` page component that calls Signup / Login.

2024-12-20 00:01 UTC, ahmad-abdelraheem commented
One last thing, Header should not be displayed on the Auth page so please update you routing to fix that. Also I prefer using hash routing as it will help as on production.

Please use Hash Routing  instead of Browser Routing ASAP since I am planning to deploy the project in the next weeks.

2024-12-20 08:01 UTC, kafkacs commented
@ahmad-abdelraheem thank you for the review, you're right I did some enhancements like:
1-made a input field component
2-made a separate Login/Signup components
3-made some enhancements on the UI
4-deleted the old signup gape
5-fixed the routes on the auth page 

as for the UI i think this one is the best for the current theme + background of the website.
check again and please let me know for any further changes.

2024-12-22 01:11 UTC, ahmad-abdelraheem requested changes
The PR is a way cleaner now, but we still have to address some changes. 

And again the view is not meeting the design. I am not talking about the background and colors, I need to meet the transition.

The form should move right and left not the entire container. Let's discuss the deference in today's meeting (Dec 22).

2024-12-22 01:11 UTC, ahmad-abdelraheem commented on FrontEnd/src/components/SignUpForm.tsx
Can we render the signup form dynamically based on an object that holds metadata? If we can achieve this, it would empower our system to customize the signup form directly through the admin system.

This is an exciting challenge. Let's take it on! For now, we can define a static object to hold the necessary data, which can later be replaced with data fetched from an API when it becomes available.

2024-12-22 01:11 UTC, ahmad-abdelraheem commented on FrontEnd/src/pages/Auth.tsx
> +export default function Login() {
```suggestion
export default function Auth() {
```
Component name should match the file name, and it's a little bit confusing to have `Login` components that holds the ` SignupForm`. If we faced a bug on signup, the last component we will check is the Login component.

2024-12-22 01:11 UTC, ahmad-abdelraheem commented on FrontEnd/src/pages/Auth.tsx
> +    navigate("/profile");
navigation should depends on the value that returned from the login/signup function.

2024-12-22 01:11 UTC, ahmad-abdelraheem commented on FrontEnd/src/pages/Auth.tsx
> +            {!isSignUp ? (
Prepare this before the ` return ` and store the `JSX` in a variable. we need the ` return ` statement as short as we can. And let's avoid code duplication such as lines 38 & 52 and lines 50 & 54.

2024-12-22 01:19 UTC, ahmad-abdelraheem commented
![image](https://github.com/user-attachments/assets/c693cec3-a65b-4a46-985d-8e318a57b179)

This package is messing from ` package.json `, please install it with ` --save-dev ` to save it as dependencies in the `  package.json ` file

```bash
 npm install --save-dev react-icons
```

2024-12-26 17:52 UTC, ahmad-abdelraheem approved these changes

2024-12-26 17:53 UTC, merged